
title: My Resume
url: 'http://junlulocky.com'
baseurl: 'Site' #change it according to your repository name



# Profile information
yourname: Harishkandan Somasundaram  ## put your name
title: 'Aspiring data scientist'  ## your title
location: Mumbai, India


## Social Profiles
quora: https://www.quora.com/profile/Harish-Kandan  ## your facebook account url
twitter: https://twitter.com/v_for_venData  ## your twitter account url
linkedin: https://www.linkedin.com/in/harishkandan  ## your linkedin account url
medium: https://medium.com/@harishkandan95  ## you dribbble account url
github: https://github.com/harishkandan  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
